# Generated by Django 3.2.11 on 2022-02-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_With_Necessary_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list', models.CharField(max_length=100)),
            ],
        ),
    ]
