# Generated by Django 3.2.11 on 2022-02-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_With_Necessary_CRUD', '0002_task_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custem', models.CharField(max_length=100)),
            ],
        ),
    ]
