# Generated by Django 3.2.11 on 2022-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_With_Necessary_CRUD', '0003_custem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custem',
            name='custem',
            field=models.CharField(max_length=50),
        ),
    ]
